name: CI

on:
  schedule:
    - cron: "0 1-23 * * *"
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{secrets.TOKEN}}
    timeout-minutes: 59
    steps:
      - uses: actions/checkout@v3
      - name: install requirements.txt
        run: pip install -r requirements.txt
      - name: entering Da Hood !
        run: |
          while true
          do
          python3 main.py
          kill $!
          done
